# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
auto_detect_solc = false
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
evm_version = "paris"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
fuzz = { runs = 1_000 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "out"
script = "script"
solc = "0.8.22"
src = "src"
test = "test"

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
base_sepolia = { key = "${API_KEY_BASESCAN}", url = "https://api-sepolia.basescan.org/api" }
base_mainnet = { key = "${API_KEY_BASESCAN}", url = "https://api.basescan.org/api" }
rise_testnet = { key = "${API_KEY_BASESCAN}", url = "https://explorer.testnet.riselabs.xyz/api?" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[profile.http_rpc]
request_timeout = 30000
retry_count = 5
retry_backoff = 1000
batch_size = 1000
headers = { "Content-Type" = "application/json" }

[profile.web]
cors = true
port = 8545
host = "127.0.0.1"
api = ["eth", "web3", "net"]
gas_limit = "30000000"
timeout = 30000

[rpc_endpoints]
localhost = "http://localhost:8545"
mainnet = "https://1rpc.io/eth"
goerli = "https://rpc.ankr.com/eth_goerli"
mumbai = "https://polygon-testnet.public.blastapi.io"
optimism_mainnet = "https://mainnet.optimism.io"
optimism_testnet = "https://goerli.optimism.io"
arbitrum_mainnet = "https://arb1.arbitrum.io/rpc"
arbitrum_testnet = "https://sepolia-rollup.arbitrum.io/rpc"
cronos_testnet = "https://evm-t3.cronos.org"
cronos_mainnet = "https://1rpc.io/cro"
scroll_testnet = "https://sepolia-rpc.scroll.io/"
metis_testnet = "https://goerli.gateway.metisdevops.link"
base_goerli = "https://goerli.base.org"
base_sepolia = "https://sepolia.base.org"
mantle_testnet = "https://rpc.testnet.mantle.xyz"
taiko_testnet = "https://rpc.jolnir.taiko.xyz"
gnosis = "https://rpc.gnosischain.com/"
gnosis_testnet = "https://rpc.chiadochain.net"
sepolia = "https://1rpc.io/sepolia"
thundercore_testnet = "https://testnet-rpc.thundercore.com"
linea_testnet = "https://rpc.goerli.linea.build"
celo_testnet = "https://alfajores-forno.celo-testnet.org"
polygon_zkvm_testnet = "https://rpc.public.zkevm-test.net"
holesky = "https://1rpc.io/holesky"
rise_testnet = "https://testnet.riselabs.xyz"
